# Generated by Django 5.1.1 on 2024-09-19 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panchayath', models.CharField(choices=[('P1', 'Panchayath 1'), ('P2', 'Panchayath 2')], max_length=50)),
                ('ward', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=50)),
                ('mahallu_number', models.CharField(max_length=50)),
                ('mahallu_area', models.CharField(max_length=100)),
                ('living_standard', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], max_length=1)),
                ('head_of_house', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(choices=[('Husband', 'Husband'), ('Wife', 'Wife'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Other', 'Other')], max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('age', models.IntegerField()),
                ('is_married', models.BooleanField(default=False)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('institution', models.CharField(blank=True, max_length=100, null=True)),
                ('education_qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('job_country', models.CharField(blank=True, max_length=100, null=True)),
                ('job_location', models.CharField(blank=True, max_length=100, null=True)),
                ('job_sector', models.CharField(blank=True, max_length=100, null=True)),
                ('job_experience', models.CharField(blank=True, max_length=100, null=True)),
                ('is_government_job', models.BooleanField(default=False)),
                ('is_expat', models.BooleanField(default=False)),
                ('is_entrepreneur', models.BooleanField(default=False)),
                ('is_businessman', models.BooleanField(default=False)),
                ('is_job_seeking', models.BooleanField(default=False)),
                ('is_chronic_patient', models.BooleanField(default=False)),
                ('disease_details', models.TextField(blank=True, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='mahallu.household')),
            ],
        ),
    ]
