# Generated by Django 5.1.1 on 2024-09-19 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahallu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='head_of_house',
        ),
        migrations.RemoveField(
            model_name='household',
            name='living_standard',
        ),
        migrations.AddField(
            model_name='household',
            name='head_of_household',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='household',
            name='standard_of_living',
            field=models.CharField(choices=[('high', 'ഉയർന്നത്'), ('medium', 'ഇടത്തരം'), ('low', 'താഴ്ന്നത്')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='household',
            name='house_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='household',
            name='mahallu_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='household',
            name='panchayath',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='household',
            name='ward',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship_to_head', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('is_married', models.BooleanField(default=False)),
                ('studying_course', models.CharField(blank=True, max_length=100, null=True)),
                ('institution', models.CharField(blank=True, max_length=100, null=True)),
                ('education_qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('country_of_job', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_job', models.CharField(blank=True, max_length=100, null=True)),
                ('job_sector', models.CharField(blank=True, max_length=100, null=True)),
                ('job_experience', models.IntegerField(blank=True, null=True)),
                ('is_government_employee', models.BooleanField(default=False)),
                ('is_expat', models.BooleanField(default=False)),
                ('is_entrepreneur', models.BooleanField(default=False)),
                ('is_business_owner', models.BooleanField(default=False)),
                ('is_looking_for_job', models.BooleanField(default=False)),
                ('is_chronic_patient', models.BooleanField(default=False)),
                ('chronic_disease_info', models.TextField(blank=True, null=True)),
                ('is_differently_abled', models.BooleanField(default=False)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='mahallu.household')),
            ],
        ),
        migrations.DeleteModel(
            name='FamilyMember',
        ),
    ]
