# Generated by Django 5.1.1 on 2024-09-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahallu', '0002_remove_household_head_of_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='house_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='whatsapp_number',
            field=models.IntegerField(),
        ),
    ]
