# Generated by Django 5.1.1 on 2024-10-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahallu', '0003_alter_household_house_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='house_name',
            field=models.CharField(default='Default House Name', max_length=100),
        ),
    ]
