# Generated by Django 5.1.1 on 2024-10-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahallu', '0004_household_house_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='house_name',
            field=models.CharField(max_length=100),
        ),
    ]
